### ISSUE TITLE
pandas error

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [vrmarcelino/CCMetagen#10]
Hi,

any idea what causes this pandas error when running CCMetagen? N.B. for this run I want all hits, hence -d 1

Thanks,

Theo

CCMetagen.py -i 1.kma.res -o results -d 1

Traceback (most recent call last):
  File "/stornext/HPCScratch/home/allnutt.t/bin/CCMetagen/CCMetagen.py", line 190, in <module>
    df = pd.read_csv(f, sep='\t', index_col=0, encoding='latin1')
AttributeError: module 'pandas' has no attribute 'read_csv'

**Comment by vrmarcelino** [comment]
Hi Theo,

I haven't seen this before but I think it is a conflict between the pandas module and other files in your system.
A few options to debug:

What do you see when you load pandas?

```
>>> import pandas
>>> pandas
```

Maybe you are importing a different pandas module.
Could you also check the its version? `>>> pandas.__version__`

Could you try to reinstall it? If you use pip, you could use:
```
pip install pip-autoremove
pip-autoremove pandas -y
pip install pandas
```

Note: the -d is minimum depth, so setting it to 1 will make the analyses more conservative and you will get fewer hits. To disable this depth-filtering step, use '-d 0'. 
You can also use '-off y' to disable the similarity thresholds.

**Comment by theo-allnutt-bioinformatics** [comment]
Using autoremove and reinstalling seemed to work. Thanks.

**Comment by theo-allnutt-bioinformatics** [comment]
I am not sure I understand what you are saying about -d 1.

In the manual it says it is the minimum depth filter, being the number of mapped nucleotides / length of 'target' (still not sure what the target is, presumably it's the sequence that the read maps to and is the same length as the read). So for a good match, the coverage should be 100 (full length mapping), and for at least one read mapped, d=1. Therefore to output equivalent of other classifiers with 'no abundance filter' c=100, d=1? Is this not correct, and if not, can you explain why please?

Thanks very much,

Theo

**Comment by vrmarcelino** [comment]
Hi Theo!

Depth is not a proportion, it can go well beyond 100. The proportion you are referring to is "coverage".
As you said, depth is the number of nucleotides / length of the template. That is correct, template is the reference sequence to which the reads are mapping to. So, if you have 500 reads of 150bp mapping to a gene that is 200bp long, the depth will be 375 (500*150 / 200).

**Comment by theo-allnutt-bioinformatics** [comment]
But how does this work if the 'template' is a whole reference genome chromosome?

**Comment by vrmarcelino** [comment]
Hi!
The process is the same if you have whole chromosomes or contigs/scaffolds of reference genomes. If you have, say, 100 reads mapping to a full chromosome of species A, and the 400 reads mapping to a single marker gene of species B (the only gene available for species B), you will get a much smaller depth for species A than B. I find this is usually the desirable outcome, as you expect to map more reads if you have more reference sequence material. This behaviour can be disabled by changing the depth unit.
We came across a situation where we sequenced the microbial community associated with a few algae. The problem was that some of these algae had chloroplast genomes available and some didn’t, so the proportion of reads assigned to these different algae was inevitably biased by the amount of reference sequences available. It is convenient to check the template length if you think you may have this issue, or try using ‘--depth_unit nc’
