### ISSUE TITLE
Abundance Calculation

### ISSUE THREAD

**Issue by punnettsun** [vrmarcelino/CCMetagen#16]
Hello again!

I have a question about the CCMetagen tutorial. I see the bar graphs in R where you have the samples on the X-axis and the abundances in the Y-axis. How exactly are the abundances calculated at each taxonomic level? I'm not sure if the abundance in the R plot is referring to the same "abundance" as the "depth" variable from kma? 

I was trying to understand the tutorial, but it seems that in the "Produce summary table" section of the tutorial, the link to the example file gives a 404 error. It would be great if you could clarify how abundances at each taxonomic level are calculated (for species, genus, etc.). Are they aggregated abundances where abundances from species level are aggregated into the genus level or are all taxonomic abundances separate from one another? I hope my question makes sense.

Thank you very much!

**Comment by vrmarcelino** [comment]
Hi!

The CCMetagen_merge script will sum the abundance at the lowest possible taxonomic rank (or the rank specified with the '--tax_level' flag). Hits that do not get to this taxonomic level will be classified at a higher taxon rank. Yes, it is the same as 'depth' from KMA.

Thanks for pointing out the broken link! I updated it and it should be working now. However, that table was done with an older version of CCMetagen. The most recent ones will also include taxa that were classified at higher taxon levels. 

For example, if you merge samples at Species level, besides the species-level abundances, you will also get the abundance of taxa classified at the genus-level only:

Sample1 | Sample2 | Superkingdom | Kingdom | Phylum | Class | Order | Family | Genus | Species
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 14.55 | Archaea | unk_k | Euryarchaeota | Methanobacteria | Methanobacteriales | Methanobacteriaceae | Methanobrevibacter |  
10.81 | 0 | Archaea | unk_k | Euryarchaeota | Methanobacteria | Methanobacteriales | Methanobacteriaceae | Methanobrevibacter | unk_s

By default, the genus-level abundance is not the sum of all abundances at the genus-level. In the example above, Sample1 has 0 abundance for the genus Methanobacteriaceae (because the abundance is computed at the species level). 

If you want all abundances at the genus level, you can use --tax_level Genus.

You might want to merge the blank cells and the "unk_s" in this case. The difference notations are to differentiate when the match was > 98% similar to a reference sequence (it gets an 'unk_s' when this reference sequence does not have a species-level name), from when it was between 96% and 98% similar (gets a blank, to indicate that you have a truly novel sequence).

Hope this makes sense.

**Comment by punnettsun** [comment]
Thank you for updating the link. I can see how the tutorial works now. I also was able to understand how --tax_level works. What I am still slightly confused about is the abundance. The default "depth" calculation for KMA & CCMetagen is "counting the number of nucleotides matching the reference sequence" with a correction for template length. So my understanding (from looking at Figure 1 part b in the CCMetagen paper) is that the number of nucleotides is referring to all of the nucleotides of all the reads that map to the highest scoring template, with the correction for the template length.  Is this the proper way of thinking about it?

Thank you.

**Comment by vrmarcelino** [comment]
Yes, that is correct. If you have several 'templates' for the same species (e.g. several genes), then depth will be the sum of all nucleotides that aligned to each gene, divided by their length.

**Comment by punnettsun** [comment]
Great, thank you for your quick responses!
