### ISSUE TITLE
Machine specs for making a large custom database

### ISSUE THREAD

**Issue by akramirez** [vrmarcelino/CCMetagen#20]
Hello,

I'm trying to make an updated database on the most recent NCBI collections, however I'm running into out of memory issues on a machine with 4 TB of memory. I still run into memory issues even when I subset to the genomes I'm most interested in (~2000 fungal representative genomes) with the command "kma_index -i genbank_fungi.fna -o genbank_fungi -NI -Sparse TG".  

Do you happen to know the machine specs used in the CCMetagen publication when making the refseq and nt databases? Or, do you have any suggestions on making databases of this size?

**Comment by vrmarcelino** [comment]
Hi!

4TB should be more than enough memory. How large is the fasta file you are using to index the db?
We had a machine with 6TB but I don't remember using more than 2TB, most databases would index with 500Gb.

The latest versions of KMA are more stable and more memory efficient - so could you try to update it?  The only difference is that you will run "kma index" instead of "kma_index"

Let us know how it goes!

**Comment by akramirez** [comment]
My fasta file for the fungal subset is ~90 GB and I'm using the most recent version of kma (1.3.4). I eventually narrowed the problem down to one genome. It seems kma index always fails (Error 12: Cannot allocate memory) with this one 2 Gbp genome, even if it's by itself. It looks like it works if I truncate it down to 1 Gbp. This particular assembly is pretty abysmal, so I'm fine with throwing it out. Note that in this work, I was trying to avoid dealing with scaffolds with a hack by merging all the scaffolds together per assembly. I can work with scaffolds instead and make some sensible post-processing.

However, I am wondering is there an upper limit in kma index to how long a single scaffold can be?

**Comment by vrmarcelino** [comment]
Hi,

Glad you found the issue! I am checking with Philip on whether there is a limit on genome size, but I suspect that the size of the scaffold is not the problem.

Regarding merging the scaffolds - are you doing that because you have multiple strains of the same species? 
If the idea is to get a strain/genome-level classification, I find it easier to index the database with the contigs separately, but named in a way where you can merge them later on. For example:

>74426\|Collinsella_aerofaciens\|GUT_GENOME096128\|GUT_GENOME096128_10
>74426\|Collinsella_aerofaciens\|GUT_GENOME096128\|GUT_GENOME096128_11
>74426\|Collinsella_aerofaciens\|GUT_GENOME096128\|GUT_GENOME096128_14


Where "GUT_GENOME096128" is the genome ID, and "GUT_GENOME096128_XX" is the contig ID.
Then you use CCMetagen_merge.py with the '-t Closest_match' flag, and merge the genomes in by their ID in R or something else. Note that you need the taxid as well.

**Comment by akramirez** [comment]
For scaffolds, yeah that was one of the reasons. Now I'm running into an unusually long running time (~2 hours on the assembly step for ~5e7 reads, only to be met with a segfault error) with kma when I try to use the database made from merged scaffolds, so I'll look into the merge script and revisit working with scaffolds which will hopefully bypass the problem.

**Comment by ptlcc** [comment]
Hi,

There is an upper limit of individual sequence lengths on most alignment tools on ~2 gbp (2147483648 bp to be exact), which is also true for kma. 
I have seen the issues as you probably have with bad scaffolding, which why I usually use the contigs with some rough filtering instead instead. If you merge your scaffolds as you suggest you will loose alignments on the edges of the original scaffolds and slow down the alignment and index building significantly.

Best,
Philip

**Comment by akramirez** [comment]
I see, although it's not immediately obvious why we'd be limited to 2e32 bp. I'll add some filtering in addition to working with scaffolds. Thanks for the help!
