### ISSUE TITLE
how to represent top most abundant species

### ISSUE THREAD

**Issue by saras224** [vrmarcelino/CCMetagen#26]
Hi 
I want to represent top 25 species from all the samples. I have a merged file which is a text file, has rows as the species and columns as the samples and values are the relative abundances. Now how can I select top 25 abundant species from all the samples?

Thanks
Saraswati

**Comment by vrmarcelino** [comment]
Hi Saraswati!

The post-processing of taxonomic assignments is not covered within the functionality of CCMetagen, but there are many ways you can do this. R is my favourite. Have a look at PhyloSeq and other programs R modules. The CCMetagen output you have can be used as an "otu table" for PhyloSeq.

We also have a tutorial here: https://github.com/vrmarcelino/CCMetagen/tree/master/tutorial,  it is a bit outdated as the CCMetagen output changed slightly since I wrote it (and PhyloSeq probably changed as well) - in this new version you will need to handle the rows with unclassified tax ranks (e.g. unknown species of genus X) in the way that best works for you. I hope the tutorial will help you to get started.

Vanessa

**Comment by saras224** [comment]
Thank you so much for your response. It was really helpful.
Saraswati Awasthi
