### ISSUE TITLE
Segmentation error in KMA 

### ISSUE THREAD

**Issue by taniagmangolini** [vrmarcelino/CCMetagen#41]
Hello,

Hi, I am facing the following error when running KMA:

Reading inputfile: /tmp/scratch/xxxxx-static/tania/scaffolds_filtered.fasta
Total time used for DB loading: 77.08 s.
...
Score collection done
Sort, output and select k-mer alignments.
Total time for sorting and outputting KMA alignment 0.31 s.
Doing local assemblies of found templates, and output results
/tmp/tmp.XXXiEkrrN/batch-file-temp: line 82: 183 Segmentation fault (core dumped) kma -i /tmp/scratch/xxxxtania/scaffolds_filtered.fasta -o teste_scaffolds.kmaout -t_db access-vpc-cromwell-sxxxxx/db/compress_ncbi_nt_no_env_11jun2019/ncbi_nt_no_env_11jun2019 -t 12 -1t1 -mem_mode -ef

The multifasta input file (approximatelly 11MB) has 545 scaffolds. The largest one's size is 536704 and the smallest one's size is 200. The machine has 250 GB RAM. Inspecting the container running this task I found that the cpu use is intense, but memory is not achieving 100%.

Do you have any ideia about what could be happening here? Thanks a lot.

**Comment by taniagmangolini** [comment]
I could run the file without errors when the thread number was set to 1.

**Comment by ptlcc** [comment]
Hi Tania

It might be an error that has been fixed in a later version, there has been some refinement of the code since 1.3.23. The newest version is 1.4.6, can I get you to try that.

Unrelated to the error, I would recommend adding the “-ca” option for long input sequences. As this will allow circular alignments in the cases where the sequences span e.g. oriT.

Best,
Philip

**Comment by taniagmangolini** [comment]
Thanks, I am going to update KMA to the last version.
