### ISSUE TITLE
Found very few number of fungi

### ISSUE THREAD

**Issue by DrYoungOG** [vrmarcelino/CCMetagen#45]
Hello, CCMetagen team!

I have installed and run CCMetagen, but only three fungi were identified at species level.
Is this normal? How many species of detected fungi are generally considered normal?

In this analysis, I have a total of 338 paired-end metagenome raw sequencing files from 169 human stool samples detected by Illumina, and the size of each fastq metagenome raw sequencing file is between 12-21G. The reference database used in CCMetagen was ncbi_nt_no_env_11jun2019.

Thanks for your help!

**Comment by vrmarcelino** [comment]
Hi!

I think that is normal. I also found very few fungal species in the few samples of human stool that I analysed with CCMetagen. 

See additional file 3 of this paper: https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-6592-2
The sequencing was much shallower than the one you have, but we could not identify any fungi at species level.
I think the problem is a combination of not having enough fungal reads in metagenomes of stool + the NCBI database not having enough fungal reference sequences (they are largely limited to marker genes).

You can use the '--tax_level Closest_match' flag to get the closest fungal reference sequence, or turn off the similarity threshold to force a species-level classification.
